### ISSUE TITLE
关于train时的报错

### ISSUE THREAD

**Issue by qianxule** [ZhenboSong/RobustSIRR#1]
![image](https://github.com/ZhenboSong/RobustSIRR/assets/127176364/a9e5632c-e821-4efd-927f-fb95a50e0b54)
训练的时候这一块有误，请问一下这一块如何进行修改

**Comment by yaoxinreaps** [comment]
你的batchsize应该是1或2吧？可以在“for label in set(labels)”前面先定义anchor_positive和negative_indices为[]。

**Comment by Liar-zzy** [comment]
> ![image](https://private-user-images.githubusercontent.com/127176364/315908635-a9e5632c-e821-4efd-927f-fb95a50e0b54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MDAwMjEsIm5iZiI6MTcxMzU5OTcyMSwicGF0aCI6Ii8xMjcxNzYzNjQvMzE1OTA4NjM1LWE5ZTU2MzJjLWU4MjEtNGVmZC05MjdmLWZiOTVhNTBlMGI1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQwNzU1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMTQzMDNkMTIxOTlmNzc2ZWQ0MGMwZDg1ZTk4NDUzYzBlNDFlMmMxMTU1NzkyZjgyN2ExMDUxNjE1NDBlYzBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PdN9fckCf0-sGRIhiyyJGxN9eaAeVG3rgE46hWd_arA) 训练的时候这一块有误，请问一下这一块如何进行修改

参考 @yaoxinreaps https://github.com/ZhenboSong/RobustSIRR/issues/1#issuecomment-2017309535 的回答，可以将batchsize调大来训练
